# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/parser.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(551, 479)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.subreddits = QtWidgets.QTextEdit(self.centralwidget)
        self.subreddits.setGeometry(QtCore.QRect(10, 10, 321, 441))
        self.subreddits.setObjectName("subreddits")
        self.use_date = QtWidgets.QCheckBox(self.centralwidget)
        self.use_date.setGeometry(QtCore.QRect(387, 120, 125, 20))
        self.use_date.setObjectName("use_date")
        self.first_date = QtWidgets.QDateEdit(self.centralwidget)
        self.first_date.setGeometry(QtCore.QRect(410, 34, 110, 22))
        self.first_date.setObjectName("first_date")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(367, 27, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(367, 74, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.second_date = QtWidgets.QDateEdit(self.centralwidget)
        self.second_date.setGeometry(QtCore.QRect(410, 80, 110, 22))
        self.second_date.setObjectName("second_date")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(390, 400, 121, 41))
        self.start.setObjectName("start")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(400, 170, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.profile = QtWidgets.QComboBox(self.centralwidget)
        self.profile.setGeometry(QtCore.QRect(390, 220, 131, 22))
        self.profile.setObjectName("profile")
        MainWindow.setCentralWidget(self.centralwidget)
        self.action123 = QtWidgets.QAction(MainWindow)
        self.action123.setObjectName("action123")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Parser"))
        self.use_date.setText(_translate("MainWindow", "Использовать дату"))
        self.label_2.setText(_translate("MainWindow", "По"))
        self.label_3.setText(_translate("MainWindow", "С"))
        self.start.setText(_translate("MainWindow", "Старт"))
        self.label_5.setText(_translate("MainWindow", "Аккаунт"))
        self.action123.setText(_translate("MainWindow", "123"))
