# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/sender.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(609, 481)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.list_messages = QtWidgets.QTextEdit(self.centralwidget)
        self.list_messages.setGeometry(QtCore.QRect(10, 10, 321, 441))
        self.list_messages.setObjectName("list_messages")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(360, 30, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(360, 100, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(360, 220, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(360, 180, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(360, 260, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.profiles_btn = QtWidgets.QPushButton(self.centralwidget)
        self.profiles_btn.setGeometry(QtCore.QRect(410, 320, 121, 41))
        self.profiles_btn.setObjectName("profiles_btn")
        self.start_btn = QtWidgets.QPushButton(self.centralwidget)
        self.start_btn.setGeometry(QtCore.QRect(410, 370, 121, 41))
        self.start_btn.setObjectName("start_btn")
        self.accounts_in_work = QtWidgets.QLabel(self.centralwidget)
        self.accounts_in_work.setGeometry(QtCore.QRect(560, 180, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.accounts_in_work.setFont(font)
        self.accounts_in_work.setObjectName("accounts_in_work")
        self.accounts_used = QtWidgets.QLabel(self.centralwidget)
        self.accounts_used.setGeometry(QtCore.QRect(560, 260, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.accounts_used.setFont(font)
        self.accounts_used.setObjectName("accounts_used")
        self.messages_sent = QtWidgets.QLabel(self.centralwidget)
        self.messages_sent.setGeometry(QtCore.QRect(560, 220, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.messages_sent.setFont(font)
        self.messages_sent.setObjectName("messages_sent")
        self.limit = QtWidgets.QSpinBox(self.centralwidget)
        self.limit.setGeometry(QtCore.QRect(500, 106, 71, 22))
        self.limit.setObjectName("limit")
        self.delay = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.delay.setGeometry(QtCore.QRect(500, 36, 71, 22))
        self.delay.setObjectName("delay")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sender"))
        self.list_messages.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "Задержка"))
        self.label_7.setText(_translate("MainWindow", "Лимит"))
        self.label_8.setText(_translate("MainWindow", "Сообщения:"))
        self.label_9.setText(_translate("MainWindow", "Аккаунты:"))
        self.label_10.setText(_translate("MainWindow", "Исп. Аккаунты:"))
        self.profiles_btn.setText(_translate("MainWindow", "Профили"))
        self.start_btn.setText(_translate("MainWindow", "Старт"))
        self.accounts_in_work.setText(_translate("MainWindow", "0"))
        self.accounts_used.setText(_translate("MainWindow", "0"))
        self.messages_sent.setText(_translate("MainWindow", "0"))
